import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import WalletProviderWrapper from "./Components/WalletProvider";
import { Toaster } from "react-hot-toast"
import { ThemeProvider } from "./Components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const displayFont = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${displayFont.variable} antialiased`}
      >
        <ThemeProvider>
          <WalletProviderWrapper>
          {children}
          <Toaster 
            position="top-right"
            toastOptions ={{
              duration:4000,
              style:{
                background:'#1e293b',
                color:"#fff"
              }
            }}
          />
          </WalletProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
